# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# theme
theme = "congo"

# baseURL = "https://oscarmoreno.com/"
defaultContentLanguage = 'es'
[languages]
  [languages.es]
    contentDir = 'content/es'
    languageName = 'Español'
    weight = 1
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 2

[services]
  [services.disqus]
    shortname = 'oscarmorenocom'

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
