# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# theme
theme = "congo"

# baseURL = "https://oscarmoreno.com/"
defaultContentLanguage = 'es'
disqusShortname = "oscarmorenocom"
[languages]
  [languages.es]
    contentDir = 'content/es'
    languageName = 'Español'
    weight = 1
    [languages.es.params]
      # version 4
      googleAnalytics = "G-348254160"
      disqusShortname = "oscarmorenocom"
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 2
      [languages.en.params]
      # version 4
      googleAnalytics = "G-348254160"
      disqusShortname = "oscarmorenocom"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
