languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "Oscar Moreno | Apple Developer "
copyright = "&copy; 2024 Óscar Moreno"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
    description = "Apple Developer"

[params.author]
name = "Oscar Moreno"
image = "img/memoji-2-no-bg.png"
headline = "Articles about Apple devices programming"
bio = "Passionate about programming and tech"
links = [
  #   { apple-podcasts = "https://podcasts.apple.com/us/podcast/programando-para-apple/id1737822341" },
  #   { spotify = "https://podcasters.spotify.com/pod/show/oscarmorenodev" },
  #   { youtube = "https://youtube.com/@oscarmorenodev" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
{ github = "https://github.com/oscarmorenodev" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
{ linkedin = "https://linkedin.com/in/oscarmorenodev" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/oscarmorenodev" },
  #   { whatsapp = "https://wa.me/phone-number" },
{ x-twitter = "https://twitter.com/oscarmorenodev" },
{ email = "mailto:oscar@oscarmorenocom" }
]